#! /usr/bin/env bash

VERSION=${1:-0.10.9}
ROOT_DIR=$(realpath "$(dirname "$(realpath "${BASH_SOURCE[0]}")")/..")
TMP_DIR="$ROOT_DIR/tmp"

rm -rf "$TMP_DIR"

mkdir -p "$TMP_DIR"
wget "https://github.com/logseq/logseq/releases/download/${VERSION}/Logseq-linux-x64-${VERSION}.AppImage" -O"$TMP_DIR/logseq.AppImage"
chmod +x "$TMP_DIR/logseq.AppImage"

mkdir -p "$TMP_DIR/user-home/.logseq"
cat <<JSON > "$TMP_DIR/user-home/.logseq/preferences.json"
{
  "theme": null,
  "themes": {
    "mode": "light",
    "light": null,
    "dark": null
  },
  "externals": [
    "$ROOT_DIR"
  ]
}
JSON